### ISSUE TITLE
Ubuntu 20.04 allocates virtual memory in a non-consecutive way

### ISSUE THREAD

**Issue by gwish111** [Qcloud1223/COMP461905#11]
I had a problem similar to #10 (Also a SIGSEGV signal in setup_hash()). I tried to output how mmap maps each LOAD segment into virtual memory:
![QQ图片20211220203425](https://user-images.githubusercontent.com/56424112/146768303-2443af6d-68a2-484a-97e5-04cfbf7839fa.png)
As you can see, its default mapping starts from 0x7ffff7ffb000 but ends at 0x7ffff7fbf000. My understanding is that VirtAddr shows the offset in the virtual memory to the *first* segment, does that mean it may cause segment fault because dynamic address can't be calculated in the way that instruction tells me? Should I just hard-code the correct address, change the address parameter in mmap to force it to choose a consecutive memory spaces, or do something else to map virtual memory?

**Comment by Qcloud1223** [comment]
> Ubuntu 20.04 allocates virtual memory in a non-consecutive way

All Linux distributions could map the page wherever it wants if you feed `NULL` as the first argument to `mmap`.

>  does that mean it may cause segment fault because dynamic address can't be calculated in the way that instruction tells me

Well, the instruction *does not* tell you to map all segments anywhere you want, **just the first segment.** The following segments should be consecutive with the previous ones.

> Should I just hard-code the correct address, change the address parameter in mmap to force it to choose a consecutive memory spaces

Partially correct. You should force the virtual memory mappings of a shared object to be consecutive, but you should not hard-code it. You will also need the dynamic linker to load other libraries, and their layout are different from `SimpleMul.so` you meet in this test.

Or, if your *hard-code* means forcing a mapping to pin to some specific address, then yes. You will have to do it :)

> I had a problem similar to #10 (Also a SIGSEGV signal in setup_hash())

If you fail to map all the segment right, then `fill_info` will probably fail too.

**Comment by gwish111** [comment]
I solved that after specifying the mapping address of the first segment (instead of using NULL). Thanks for your help.
