### ISSUE TITLE
Test1: Wrong address returned by dlsym

### ISSUE THREAD

**Issue by xxyy-0204** [Qcloud1223/COMP461905#13]
As I use dlsym to find the address of string "puts", the address returned is `0x7ffff785eaa0` 
While the base_address in my program is `0x7ffff7ff5000`, and regard to "puts" offset, the address should be `0x7fffff81f5018`.
I do not know whether there's something wrong... The address returned is just an illegal one... 
(ps, I got the right address of dyn)

**Comment by Qcloud1223** [comment]
Please read the instruction more carefully:

> GOT and PLT entries are like some puzzles, leaving us with some blanks to fill.
> ...
> What makes this test easier is that you already what to fill in the blank.

In this case, `0x7ffff785eaa0` is what to fill, and `0x7fffff81f5018` is the address of the blank.

**Comment by xxyy-0204** [comment]
Thank you so much！
I misunderstood the instruction. After correcting the problem，I could see the"Hello World"message now！
