### ISSUE TITLE
What is this from './build/run-openlib'？

### ISSUE THREAD

**Issue by Twinkzzzzz** [Qcloud1223/COMP461905#15]
FileNotFoundError: [Errno 2] No such file or directory: './build/run-openlib': './build/run-openlib'
When running autograder.py
(CentOS8 Python 3.6.8)
![O9$_IZNGVCQ 3_XMO1VN`LD](https://user-images.githubusercontent.com/7188904/220661590-1d3495f8-8d61-4a47-b6c5-3e58c92f5718.png)

**Comment by Qcloud1223** [comment]
Hello there, sorry I didn't respond promptly.

Could you try running `make` under root directory of the project? This should compile `./build/run-openlib`.

If that does not work, maybe you can try directly `make build/run-openlib` and check if anything shows up in `build/`.

**Comment by Twinkzzzzz** [comment]
Thanks a lot!
And I have another question......about test2
The instruction means that we should get the entry of the init function and call it by ourselves(It means to call it in our code section), Is that right? Or we only need to fininsh the relocation of local symbols and the programme will call the init function by itself?

**Comment by Qcloud1223** [comment]
> Thanks a lot! And I have another question......about test2 The instruction means that we should get the entry of the init function and call it by ourselves(It means to call it in our code section), Is that right? Or we only need to fininsh the relocation of local symbols and the programme will call the init function by itself?

You should call it yourself, in `InitLibrary`.

**Comment by Twinkzzzzz** [comment]
So follow the instructions,we should find the entries in dynamic section(INIT and INIT_ARRAY), get the address of init function through the entries, and then call it.Is that right?
