### ISSUE TITLE
[problem] Offset and Alignment in ELF files

### ISSUE THREAD

**Issue by SoullAngle** [Qcloud1223/COMP461905#7]
I use "readelf -l" to read the file(SimpleMul.so)
And the result is below
```
...
Program Headers:(there are 7 program headers, I just show some of them)
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x00000000000006f4 0x00000000000006f4  R E     20000
  LOAD           0x0000000000000e30 0x0000000000200e30 0x0000000000200e30
                 0x00000000000001f0 0x00000000000001f8  RW      20000
  DYNAMIC        0x0000000000000e48 0x0000000000200e48 0x0000000000200e48
                 0x0000000000000190 0x0000000000000190  R W     8
  NOTE           0x00000000000001c8 0x00000000000001c8 0x00000000000001c8
                 0x0000000000000024 0x0000000000000024  R       4
...
```
Here, we could see that the p_align of the first and the second(LOAD) item is 20000.
According to the blog [https://blog.csdn.net/u011210147/article/details/54092405](url), we know that the align should be a power of 2, like 0x1000 etc. But here, 20000 is not a power of 2.
What's more, in the second item, the offset is 0x0..0e30, which is not a multiple of 4096. When we use mmap, the last argument--offset, must be the multiple of page size(4k), else we will get an error -- invalid argument(same problem in previous issue). In this case, should we align p_offset with page size by ourselves? By the way, there is no problem when I use mmap to load the first LOAD segment.

**Comment by SoullAngle** [comment]
Sorry, the link is here: [https://blog.csdn.net/u011210147/article/details/54092405](https://blog.csdn.net/u011210147/article/details/54092405)

**Comment by SoullAngle** [comment]
By the way, if we should align p_offset with page size by ourselves. I think the **Instruction.md** should add a sentence like _you may want to double check the first two arguments **and the last argument**.(in the test0 mmap part)._

**Comment by SoullAngle** [comment]
Maybe the align should be 0x20000 but not 20000?

**Comment by Qcloud1223** [comment]
> Maybe the align should be 0x20000 but not 20000?

Yep, And I did a really quick experiment to show you how `dlopen` map the two `LOAD` segment.
![捕获](https://user-images.githubusercontent.com/46517840/145518028-35b129cf-0942-4830-ab4f-3ba8703debb0.PNG)
You can see that the second segment is off by `0x20000`.

In fact, my `readelf` even print `offset` field in hex :) FYI, its version is `2.30`.

> What's more, in the second item, the offset is 0x0..0e30, which is not a multiple of 4096. When we use mmap, the last argument--offset, must be the multiple of page size(4k), else we will get an error

You are right, `mmap` requires its argument `offset` to be aligned to page boundary. However, the `offset` field printed by `readelf` indicates the starting byte of that segment, and **a file does not have to know anything about virtual memory**, so that it is not aligned to any page, but only the alignment requirement from the file itself, as below:

As for the `alignment` field in `readelf`, it is mainly a restriction for `VirtAddr`. `VirtAddr % Alignment == Offset % Alignment` must apply, as the manual of elf says:
>              p_align
>              This member holds the value to which the segments are
>              aligned in memory and in the file.  Loadable process
>              segments must have congruent values for p_vaddr and
>              p_offset, modulo the page size.  Values of zero and one
>              mean no alignment is required.  Otherwise, p_align should
>              be a positive, integral power of two, and p_vaddr should
>              equal p_offset, modulo p_align.

> In this case, should we align p_offset with page size by ourselves?

Yes. 

I might draw a picture to help you better understand it, but I also think that words suffice for explanation.

> I think the Instruction.md should add a sentence like you may want to double check the first two arguments and the last argument

Good idea. I were thinking about the first two arguments when I wrote that.

Let me know if you have further issues, and I can close this issue or provide more info.

**Comment by SoullAngle** [comment]
One more question. In file SimpleMul.so, there are 7 segments in total. They have different types like LOAD, DYNAMIC, NOTE, etc. 
In **Instruction.md**,  you said obviously the LOAD segment should be loaded. I think the DYNAMIC segment should also be loaded. And should we load other segments like NOTE...? 
My Conception:
For test0, I just need to load the LOAD segment and DYNAMIC segment and allocate the correct address for them. Then I just need to store the base address in addr, and store the DYNAMIC real address in dyn?

**Comment by SoullAngle** [comment]
> My Conception: For test0, I just need to load the LOAD segment and DYNAMIC segment and allocate the correct address for them. Then I just need to store the base address in addr, and store the DYNAMIC real address in dyn?

Oops, I know....
**I don't call the helper function....** 
I were thinking the code frame will call them automatically. (my fault)
But I still want to confirm my conception.

**Comment by Qcloud1223** [comment]
> I think the DYNAMIC segment should also be loaded.

Actually, we've already done that! Taking your `SimpleMul.so` as an example:

The second `LOAD` segment starts from `offset` at `0xe30`, and its `FileSiz` is `0x1f0`, which means it will take up `[0xe30, 0x1020]` in the file. Similarly, `DYNAMIC` segement takes up `[0xe48, 0xfd8]`, and this is a subset of the second `LOAD`.

You can also try with `readelf -s ./test_lib/SimpleMul.so` to see the sections making up each segment.

That is to say, segments have intersections. We are not going to discuss why it is designed like this here. But this is a great question!

> And should we load other segments like NOTE...?

No. Non-`LOAD` segments provide extra information to the dynamic linker, and in this project you do not need to consider that. In fact, `DYNAMIC` segment (you may want to distinguish it between `.dynamic` section) makes the dynamic linker know the location of `.dynamic` section, without having to traverse the second `LOAD` segment.

> My Conception:
For test0, I just need to load the LOAD segment and DYNAMIC segment and allocate the correct address for them. 

Now you know that you do not have to load `DYNAMIC` segment again. The real challenge is to map all `LOAD` segment correctly, and this will not be discussed here.

> Then I just need to store the base address in addr, and store the DYNAMIC real address in dyn?

Yes. Also don't forget to check the helper function, which setup `dyn_info` for you. In fact, `LinkMap` is a data structure storing information among all modules: `MapLibrary`, `RelocLibrary`, ... You are free to implement your own if you feel comfortable. Basically, `MapLibrary` only **requires** you to map the library.

**Comment by Qcloud1223** [comment]
![IMG_0003](https://user-images.githubusercontent.com/46517840/145544666-8a40f801-b5d8-49d3-a9ac-aaf22f128bbe.PNG)

> I might draw a picture to help you better understand it, but I also think that words suffice for explanation.

As promised, I draw a picture on this. Hope this help someone.

**Comment by SoullAngle** [comment]
Much, appreciate!
I passed test 0 successfully! But I loaded both LOAD and DYNAMIC segments(load twice). I got what you said, and I will correct my code later.

**Comment by Qcloud1223** [comment]
Congrats! I'm very happy to see that :D

**For newcomers:** @SoullAngle has asked several valuable questions, yet the way of asking can be improved. See #3 for more info.
